name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: zec/TinyTapeout/tt-gds-action@url-fix-zec
        with:
          flow: openlane2

  precheck:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: zec/TinyTapeout/tt-gds-action/precheck@url-fix-zec

  gl_test:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: zec/tt-gds-action/gl_test@url-fix-zec

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: zec/tt-gds-action/viewer@url-fix-zec
